Add ansi matrix layout for kmonad
ColemakMods/mod-dh pull request #54
Opened 2022-04-28 12:51 UTC by mhamrah

This takes the ansi layout but places the z key in its original position, shifting the bottom row over. It allows for matrix style keyboards to be laid out with the z key under the a.

2022-06-09 12:09 UTC, stevep99 requested changes
Since this is for a matrix layout (not ansi), could you just adjust it:
- rename file to "colemak-dh-matrix.kbd"
- change alignment of bottom row on mappings so that "z" is directly beneath "a", etc (since matrix boards don't have the stagger)

2022-06-10 09:25 UTC, DreymaR commented
Not sure about how KMonad goes about its business, but ANSI is kind of two things really: The board geometry, and – on Windows at least – the VK codes used. VK codes differ between ANSI and ISO, and even between different ISO locales as misfortune and poor design by Microsoft would have it.

So in some cases, it's still worth keeping the ANSI tag if VK codes are used. This is reflected in EPKL which currently uses both "ANS-Orth" and "ISO-Orth" keyboard types; I'm hoping to arrive at a better solution eventually though, since ISO isn't one standard when it comes to VK codes...!

2022-06-10 09:39 UTC, stevep99 commented
KMonad is based on remapping incoming raw keycodes, so the VK issue shouldn't be relevant here. 
The files in this repo generally follow the convention:
- "ansi" targetted at traditional ANSI boards assuming angle mod
- "iso" targetted at traditional ISO boards assuming angle mod
- "matrix" for matrix/ortho/col-stagger boards assuming NO angle mod

2022-06-10 10:09 UTC, DreymaR commented
The question isn't incoming but outgoing VK codes, in which case I should think that KMonad falls under the same curse as everything else when it comes to Windows.

But of course you're right: There should ideally be those three types and nothing more. If a user has an underlying OS layout with weird VK codes you might include instructions on how to fix it or something, as different ISO locales have a huge mess of VK code sets which you cannot hope to provide for.

2025-02-21 23:16 UTC, mhamrah commented
I apologize, I completely forgot I did this. I made the requested modifications if you're still interested.

2025-02-22 11:24 UTC, merged